version: "3.8"
services:
  # Django app
  main:
    container_name: backoffice_inventory
    labels:
      svc: backoffice_inventory
    restart: always
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8200:8000
