# Generated by Django 5.0.2 on 2024-05-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=40)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('country', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=24)),
                ('fax', models.CharField(max_length=24)),
                ('home_page', models.URLField()),
            ],
        ),
    ]
