version: "3.1"

services:
  main:
    container_name: backoffice_auth
    labels:
      svc: backoffice_auth
    restart: always
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - live_backend
    depends_on:
      - db_auth
    command:
      [
        "./wait-for-it.sh",
        "db_auth:3306",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]

  db_auth:
    container_name: backoffice_auth_db
    image: mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306
    networks:
      - live_backend
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

volumes:
  db_data:

networks:
  live_backend:
    external: true
