# Generated by Django 5.0.2 on 2024-05-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('quantity_per_unit', models.CharField(max_length=20)),
                ('unit_price', models.FloatField()),
                ('units_in_stock', models.SmallIntegerField()),
                ('units_on_order', models.SmallIntegerField()),
                ('reorder_level', models.SmallIntegerField()),
                ('discontinued', models.BooleanField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categories')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliers')),
            ],
        ),
    ]
