# Generated by Django 5.0.2 on 2024-05-10 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30, null=True)),
                ('title_of_courtesy', models.CharField(max_length=25, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=15, null=True)),
                ('postal_code', models.CharField(db_index=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=15, null=True)),
                ('home_phone', models.CharField(max_length=24, null=True)),
                ('extension', models.CharField(max_length=4, null=True)),
                ('photo', models.ImageField(default='files/users/default.webp', upload_to='files/users/')),
                ('notes', models.TextField()),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
                ('reports_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subordinates', to='user.user')),
            ],
        ),
    ]
