# Generated by Django 5.0.2 on 2024-04-27 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(db_index=True, max_length=20)),
                ('firstName', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30, null=True)),
                ('titleOfCourtesy', models.CharField(max_length=25, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('hireDate', models.DateField(null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=15, null=True)),
                ('postalCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=15, null=True)),
                ('homePhone', models.CharField(max_length=24, null=True)),
                ('extension', models.CharField(max_length=4, null=True)),
                ('photo', models.ImageField(null=True, upload_to='users')),
                ('notes', models.TextField()),
                ('photoPath', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
                ('reportsTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
    ]
