# Generated by Django 5.0.2 on 2024-04-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_photo'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reportsTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subordinates', to='user.user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('reportsTo', models.F('id')), _negated=True), name='reportsTo_not_self'),
        ),
    ]
