# Generated by Django 5.0.2 on 2024-04-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_reportsto_user_reportsto_not_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reportsTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subordinates', to='user.user'),
        ),
    ]
