# Generated by Django 5.0.2 on 2024-04-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_profile',
            new_name='idProfile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
