# Generated by Django 5.0.2 on 2024-04-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_created_at_user_createdat_and_more'),
        ('user_profile', '0002_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='reportsTo_not_self',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hireDate',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='homePhone',
            new_name='home_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idProfile',
            new_name='id_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reportsTo',
            new_name='reports_to',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='titleOfCourtesy',
            new_name='title_of_courtesy',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('reports_to', models.F('id')), _negated=True), name='reports_to_not_self'),
        ),
    ]
