# Generated by Django 5.0.2 on 2024-05-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('order_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField(db_index=True)),
            ],
            options={
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
