# Generated by Django 5.0.2 on 2024-05-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('required_date', models.DateField()),
                ('shipped_date', models.DateField()),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_name', models.CharField(max_length=40)),
                ('ship_address', models.CharField(max_length=60)),
                ('ship_city', models.CharField(max_length=15)),
                ('ship_region', models.CharField(max_length=15)),
                ('ship_postal_code', models.CharField(max_length=10)),
                ('ship_country', models.CharField(max_length=15)),
                ('employee_id', models.IntegerField(db_index=True)),
                ('customer_id', models.CharField(db_index=True, max_length=5)),
                ('ship_via', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='order.shippers')),
            ],
        ),
    ]
