# Generated by Django 5.0.2 on 2024-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orders_customer_id_alter_orders_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='freight',
            field=models.FloatField(),
        ),
    ]
