# Generated by Django 5.0.2 on 2024-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privilege',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privilege',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
