# Generated by Django 5.0.2 on 2024-04-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
    ]
