# Generated by Django 5.0.2 on 2024-05-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='fields/categories/')),
            ],
        ),
    ]
